SPRITE_SIZE = 64
SPRITE_SCALING = 2

NUMBER_OF_TRACKS = 5
NUMBER_OF_SPRITES = 5
PADDING = 16
TRACK_WIDTH = SPRITE_SIZE * SPRITE_SCALING + PADDING
TRACK_HEIGHT = TRACK_WIDTH * NUMBER_OF_SPRITES

WINDOW_WIDTH = TRACK_WIDTH * NUMBER_OF_TRACKS
WINDOW_HEIGHT = TRACK_HEIGHT

TRACK_SPEED = TRACK_WIDTH * 1.5
